Traceback (most recent call last):
  File "/Users/mmccull/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/mmccull/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/mmccull/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/mmccull/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/mmccull/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/mmccull/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/mmccull/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/mmccull/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, ax = plt.subplots(figsize=(8,6),dpi= 80, facecolor='w', edgecolor='k')
plt.tick_params(axis='both',labelsize=20)
plt.grid( which='major', axis='both', color='#808080', linestyle='--')
ax.plot(R,E_CI_Z_1,lw=4, label=r'$E_{CI}$ - $Z = 1$')
ax.plot(R,E_CI_Z_opt,lw=4, label=r'$E_{CI}$ - $Z = opt$')
ax.plot(R,E_1s_basis,lw=4, label=r'$E_{MO}$ - $Z=1$')
ax.plot(R,E_1s_opt,lw=4, label=r'$E_{MO}$ - $Z= opt$')
ax.set_xlabel(r'R/$a_0$',fontsize=20)
ax.set_ylabel(r'$E_0 (Hartree)$',fontsize=20)
plt.legend(fontsize=20)
ax2 = ax.twinx()
color = 'tab:orange'
ax2.set_ylabel('Z/e', color='gray', fontsize=20)  # we already handled the x-label with ax1
ax2.plot(R, Z_min_CI, '--', lw=3, color=color, alpha=0.75)
ax2.plot(R, Z_min_MO, '--', lw=3, color='tab:red', alpha=0.75)
ax2.tick_params(axis='y', labelcolor='gray',labelsize=20)
fig.tight_layout()
plt.title(r'Configuration Interaction Solution to the H$_2$ Molecule in Minimal Slater Basis',fontsize=16);
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/var/folders/td/dll8n_kj4vd0zxjm0xd9m7740000gq/T/ipykernel_84073/379960386.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0mplt[0m[0;34m.[0m[0mtick_params[0m[0;34m([0m[0maxis[0m[0;34m=[0m[0;34m'both'[0m[0;34m,[0m[0mlabelsize[0m[0;34m=[0m[0;36m20[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mplt[0m[0;34m.[0m[0mgrid[0m[0;34m([0m [0mwhich[0m[0;34m=[0m[0;34m'major'[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0;34m'both'[0m[0;34m,[0m [0mcolor[0m[0;34m=[0m[0;34m'#808080'[0m[0;34m,[0m [0mlinestyle[0m[0;34m=[0m[0;34m'--'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0max[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mR[0m[0;34m,[0m[0mE_CI_Z_1[0m[0;34m,[0m[0mlw[0m[0;34m=[0m[0;36m4[0m[0;34m,[0m [0mlabel[0m[0;34m=[0m[0;34mr'$E_{CI}$ - $Z = 1$'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0max[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mR[0m[0;34m,[0m[0mE_CI_Z_opt[0m[0;34m,[0m[0mlw[0m[0;34m=[0m[0;36m4[0m[0;34m,[0m [0mlabel[0m[0;34m=[0m[0;34mr'$E_{CI}$ - $Z = opt$'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0max[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mR[0m[0;34m,[0m[0mE_1s_basis[0m[0;34m,[0m[0mlw[0m[0;34m=[0m[0;36m4[0m[0;34m,[0m [0mlabel[0m[0;34m=[0m[0;34mr'$E_{MO}$ - $Z=1$'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_axes.py[0m in [0;36mplot[0;34m(self, scalex, scaley, data, *args, **kwargs)[0m
[1;32m   1630[0m         """
[1;32m   1631[0m         [0mkwargs[0m [0;34m=[0m [0mcbook[0m[0;34m.[0m[0mnormalize_kwargs[0m[0;34m([0m[0mkwargs[0m[0;34m,[0m [0mmlines[0m[0;34m.[0m[0mLine2D[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1632[0;31m         [0mlines[0m [0;34m=[0m [0;34m[[0m[0;34m*[0m[0mself[0m[0;34m.[0m[0m_get_lines[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0mdata[0m[0;34m=[0m[0mdata[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1633[0m         [0;32mfor[0m [0mline[0m [0;32min[0m [0mlines[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1634[0m             [0mself[0m[0;34m.[0m[0madd_line[0m[0;34m([0m[0mline[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_base.py[0m in [0;36m__call__[0;34m(self, data, *args, **kwargs)[0m
[1;32m    310[0m                 [0mthis[0m [0;34m+=[0m [0margs[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    311[0m                 [0margs[0m [0;34m=[0m [0margs[0m[0;34m[[0m[0;36m1[0m[0;34m:[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 312[0;31m             [0;32myield[0m [0;32mfrom[0m [0mself[0m[0;34m.[0m[0m_plot_args[0m[0;34m([0m[0mthis[0m[0;34m,[0m [0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    313[0m [0;34m[0m[0m
[1;32m    314[0m     [0;32mdef[0m [0mget_next_color[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_base.py[0m in [0;36m_plot_args[0;34m(self, tup, kwargs, return_kwargs)[0m
[1;32m    496[0m [0;34m[0m[0m
[1;32m    497[0m         [0;32mif[0m [0mx[0m[0;34m.[0m[0mshape[0m[0;34m[[0m[0;36m0[0m[0;34m][0m [0;34m!=[0m [0my[0m[0;34m.[0m[0mshape[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 498[0;31m             raise ValueError(f"x and y must have same first dimension, but "
[0m[1;32m    499[0m                              f"have shapes {x.shape} and {y.shape}")
[1;32m    500[0m         [0;32mif[0m [0mx[0m[0;34m.[0m[0mndim[0m [0;34m>[0m [0;36m2[0m [0;32mor[0m [0my[0m[0;34m.[0m[0mndim[0m [0;34m>[0m [0;36m2[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mValueError[0m: x and y must have same first dimension, but have shapes (1,) and (750,)
ValueError: x and y must have same first dimension, but have shapes (1,) and (750,)

